CREATE TABLE SCHEDULE
(
	-- Foreign keys
	CAR_PLATE  VARCHAR(12) NOT NULL,
	USER_ID    INT         NOT NULL,
	-- Rent interval
	START_TIME TIMESTAMP   NOT NULL,
	END_TIME   TIMESTAMP   NOT NULL,
	-- Additional info
	NOTES      TEXT,

	-- Primary key is the whole record
	PRIMARY KEY (CAR_PLATE, USER_ID, START_TIME, END_TIME),

	-- Foreign keys
	FOREIGN KEY (CAR_PLATE) REFERENCES CARS (PLATE)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,

	-- Check for correct interval format
	CONSTRAINT CHECK_INTERVAL CHECK (START_TIME < END_TIME)
);
