-- Start transaction
BEGIN;

-- Truncate table content before insert entire batch
TRUNCATE CARS CASCADE;

-- Insert data batch
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('BG468CC', 'Volkswagen', 'CC', 'Orange', 2012);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('JR695DA', 'Ford', 'Escort', 'Teal', 1995);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('EM688QV', 'Mercedes-Benz', 'C-Class', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('CB549RP', 'Oldsmobile', 'Ciera', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('SO798EQ', 'Ford', 'Explorer Sport', 'Crimson', 2000);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('BU718PE', 'Nissan', 'Maxima', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('IS980YR', 'Aston Martin', 'DB9', null, 2008);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('XO905ZD', 'Mitsubishi', 'Eclipse', 'Purple', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('AS039IL', 'Chevrolet', 'Astro', 'Yellow', 1997);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('HK038RY', 'Pontiac', 'Montana SV6', 'Red', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('DH413MP', 'Ford', 'E350', 'Crimson', 2010);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('TN186GI', 'Oldsmobile', 'Silhouette', 'Indigo', 1994);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('ZB791JG', 'Honda', 'Civic', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('OU033WV', 'Ford', 'Explorer', 'Khaki', 2000);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('SV959LI', 'Subaru', 'Loyale', 'Blue', 1991);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('VM663GK', 'GMC', '1500', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('VY275YQ', 'Toyota', 'Celica', 'Teal', 1983);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('SX098BS', 'Ferrari', '599 GTB Fiorano', null, 2007);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('BW485BD', 'Chevrolet', 'Malibu', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('CS934XK', 'Toyota', 'RAV4', 'Khaki', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('KK468XA', 'Pontiac', 'Grand Prix', 'Aquamarine', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('ZM603NZ', 'Nissan', 'Quest', 'Yellow', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('OX340VW', 'GMC', 'Savana 1500', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('DE756UF', 'Maybach', 'Landaulet', 'Violet', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('OR977AL', 'MINI', 'Cooper Countryman', 'Aquamarine', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('SN127YM', 'Suzuki', 'Grand Vitara', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('QE438BQ', 'Lincoln', 'MKX', 'Fuscia', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('LO126BS', 'Chevrolet', 'Silverado 3500', 'Blue', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('WM524XL', 'Dodge', 'Caliber', 'Turquoise', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('TZ204JT', 'Toyota', 'Camry', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('UH296AG', 'Audi', 'RS4', 'Indigo', 2008);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('DD530NL', 'Buick', 'Special', 'Khaki', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('KM998QN', 'Suzuki', 'Swift', 'Crimson', 1987);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('QA843JV', 'Toyota', 'T100 Xtra', 'Aquamarine', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('MK715BZ', 'GMC', 'Yukon XL 2500', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('QY222QM', 'Audi', 'R8', 'Mauv', 2010);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('RY462ZE', null, 'Cavalier', 'Goldenrod', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('ON036BF', 'Buick', 'LeSabre', 'Purple', 1987);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('DC373LA', 'Ford', 'Aspire', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('NK515UP', 'Suzuki', 'SJ', 'Fuscia', 1986);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('LD673XI', 'Mitsubishi', 'Lancer Evolution', 'Pink', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('CO480OV', 'Scion', 'xA', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('DG121ZC', 'Mazda', 'RX-7', 'Goldenrod', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('PA951BL', 'Lamborghini', 'Gallardo', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('UY272FY', 'Ford', 'Escort', 'Green', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('KL289AS', 'Mercedes-Benz', 'C-Class', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('MO880KJ', 'Toyota', 'Sienna', 'Violet', 2011);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('IN809GH', 'Chevrolet', 'Corvette', 'Goldenrod', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('OE830GJ', 'GMC', 'Vandura G2500', null, 1995);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('QN178XR', 'Chevrolet', 'Suburban 1500', 'Violet', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('XY169XU', 'Ford', 'F250', null, 2006);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('QT177YF', 'Buick', 'Somerset', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('XC538MJ', 'Chevrolet', 'Prizm', 'Orange', 2000);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('XD311MD', null, 'Corolla', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('LD560JA', 'Mitsubishi', 'Challenger', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('AI025DE', 'Toyota', null, null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('SH382UJ', 'Chevrolet', 'G-Series G30', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('DF315YQ', 'Infiniti', 'G37', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('EH464DT', null, null, null, 2003);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('TK184NW', null, 'Volt', 'Violet', 2011);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('QB364MT', 'Cadillac', 'Eldorado', 'Crimson', 1996);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('KQ474AG', 'GMC', 'Sierra 3500', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('VI569WD', 'Chevrolet', 'Suburban 1500', null, 2000);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('BV192OY', 'Maybach', '57', 'Green', 2003);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('NE193MU', null, 'Navigator L', null, 2009);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('MR934NR', 'Isuzu', 'Oasis', 'Aquamarine', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('RX374SY', 'Hummer', 'H1', 'Violet', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('GD976QK', 'Hummer', 'H2', 'Teal', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('ED189WL', 'Volvo', '960', 'Pink', 1996);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('AV616EQ', 'Mitsubishi', null, 'Violet', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('WT939YL', 'Ford', 'Freestar', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('ZH121WO', 'GMC', 'Yukon XL 1500', 'Yellow', 2009);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('MG002TB', 'Mitsubishi', 'Mirage', 'Goldenrod', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('EG326VD', 'Chevrolet', 'Corvette', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('PZ729WR', 'Chevrolet', 'Suburban 2500', 'Green', 1997);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('MO061PJ', 'Nissan', 'Pathfinder', 'Violet', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('VR174UG', 'Ford', 'Taurus', 'Yellow', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('OH561PV', 'Ford', 'Econoline E350', 'Green', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('PS958BW', 'Mitsubishi', 'Montero Sport', 'Turquoise', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('UH930WP', 'Dodge', 'Ram Van 2500', null, 1996);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('QO810IN', 'Chevrolet', 'G-Series 1500', null, 1998);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('OY632QD', 'Ford', 'Festiva', 'Maroon', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('JG317PV', 'Isuzu', 'Oasis', 'Green', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('LT363LE', 'Toyota', 'Land Cruiser', 'Blue', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('VN099KB', 'BMW', 'X5 M', null, 2011);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('EY494UD', 'Honda', 'Civic', 'Violet', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('PM177LQ', 'BMW', '6 Series', null, 2007);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('OS622BP', 'Hyundai', 'Accent', 'Red', 2013);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('EW928IV', 'BMW', null, 'Red', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('WA973JQ', 'Volkswagen', 'Fox', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('LE095KA', 'Audi', '80/90', 'Teal', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('HV027SO', 'Ford', 'Crown Victoria', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('VU302CU', 'Toyota', 'Matrix', 'Goldenrod', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('YV171OP', 'Audi', 'R8', 'Puce', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('VS716IB', 'Ford', 'Mustang', 'Blue', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('CB244RC', 'Dodge', 'Caravan', 'Puce', 2000);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('IZ243OV', 'Chevrolet', 'Blazer', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('PP881OG', 'Mercedes-Benz', 'SL-Class', null, 1992);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('FV659II', 'Saturn', null, null, 2005);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('BW915CW', 'Rolls-Royce', 'Ghost', 'Khaki', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('DU724MT', 'Chevrolet', 'Camaro', 'Turquoise', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('NR491FT', 'Chevrolet', 'S10 Blazer', 'Violet', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('JQ077OT', 'Volkswagen', 'GTI', 'Red', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('OH687OF', 'Subaru', null, null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('KQ089BR', 'Chevrolet', '1500', 'Teal', 1997);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('KN799LM', 'Toyota', 'Tacoma Xtra', 'Blue', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('HS102NH', 'Mercury', 'Grand Marquis', 'Fuscia', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('OU103DR', 'Toyota', 'Highlander', 'Fuscia', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('SH777RT', 'GMC', 'Savana 3500', null, 2008);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('RG114KR', 'Mitsubishi', 'Eclipse', null, 1989);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('GZ382FR', 'Ford', 'E150', 'Indigo', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('HS422WC', 'Chrysler', '300M', 'Indigo', 2004);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('KJ835HU', 'Pontiac', 'G8', 'Purple', 2008);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('KE425XY', 'Buick', 'LeSabre', 'Puce', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('CB153ZI', 'Hyundai', 'Tiburon', 'Red', 1998);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('MZ314GS', 'Mercury', 'Mountaineer', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('RV691EV', 'Ford', 'Explorer', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('WH678TH', 'Nissan', 'Xterra', 'Fuscia', 2011);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('AG853YF', 'Mercury', 'Grand Marquis', 'Khaki', 1988);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('YA606XW', 'Toyota', 'Highlander', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('VA652QF', 'Porsche', 'Boxster', 'Red', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('LT392TG', 'Chevrolet', 'Tahoe', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('OC132GC', 'GMC', 'Yukon XL 1500', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('ZJ447UH', 'Lincoln', 'Continental', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('YX811OM', 'Pontiac', 'Grand Prix', 'Purple', 1966);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('KX731RO', 'Chevrolet', 'Astro', 'Fuscia', 1996);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('NP432RC', 'GMC', '2500 Club Coupe', 'Crimson', 1998);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('QF556ME', 'Honda', 'Passport', 'Puce', 2001);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('TP645LI', 'Buick', 'Riviera', 'Blue', 1979);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('DR079EN', 'Toyota', 'Camry', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('IE248FG', 'Porsche', '911', 'Puce', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('GY463ZP', 'Volkswagen', 'Eurovan', 'Red', 1997);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('HW639TU', 'Nissan', 'Rogue', 'Goldenrod', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('PT317KE', 'Ford', 'Explorer', 'Crimson', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('TW172SJ', 'Suzuki', 'Vitara', 'Indigo', 2000);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('KQ693KE', 'Chevrolet', null, null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('WY993TH', null, 'Z4 M', null, 2009);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('UD392NT', 'Nissan', '300ZX', 'Orange', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('IC436OR', 'Toyota', 'Tundra', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('AR699YG', 'Subaru', 'Outback', 'Teal', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('QE764YK', 'Pontiac', 'Bonneville', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('FQ358PR', 'Volvo', 'S80', 'Turquoise', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('RJ550PQ', 'Ford', 'Tempo', 'Pink', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('AG578YR', 'Buick', 'Riviera', 'Violet', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('UQ043NL', 'Mercedes-Benz', 'SL-Class', null, 1989);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('RI329ZS', 'Ford', 'E-Series', 'Red', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('UH493DA', 'Pontiac', 'Trans Sport', 'Fuscia', 1991);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('BZ207KW', 'Chevrolet', 'G-Series G20', 'Red', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('CI769BW', 'Toyota', 'Prius', 'Turquoise', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('RD068NU', 'Lincoln', 'Town Car', 'Goldenrod', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('VF419XZ', 'Chevrolet', null, 'Aquamarine', 2001);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('AT735ES', 'Chevrolet', 'Express 1500', 'Crimson', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('YA717UO', 'Kia', 'Sorento', 'Khaki', 2005);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('CL892GA', 'Saab', '9-7X', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('ZD855EZ', 'Hyundai', 'Tucson', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('WO642HV', 'Volkswagen', 'Jetta', 'Mauv', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('WE212DV', 'Ford', 'Mustang', 'Mauv', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('YK303ZK', 'Chevrolet', 'Venture', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('PJ108KT', 'Mitsubishi', 'Tredia', 'Aquamarine', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('OQ026HK', 'Mercury', 'Sable', 'Maroon', 2009);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('QX407YI', 'Ford', 'F350', 'Indigo', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('KM579XU', 'Mazda', 'Miata MX-5', null, 1995);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('NK844LM', 'Volkswagen', 'Rabbit', 'Purple', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('IX376EC', null, 'Sable', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('XB509QV', 'MINI', 'Countryman', 'Puce', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('IF714HX', 'Mercury', null, null, 1991);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('ZQ294FV', 'Chevrolet', 'Caprice', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('LN261IT', 'Suzuki', 'Reno', 'Violet', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('ZW424WR', 'Subaru', 'Legacy', 'Turquoise', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('OW438UC', 'Subaru', 'Forester', 'Pink', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('MX133KY', 'Ford', 'Tempo', 'Fuscia', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('HY312WL', 'Hyundai', 'Entourage', 'Mauv', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('BY020GT', 'Toyota', 'Tercel', 'Yellow', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('JB275FA', 'Mazda', 'RX-8', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('DW551KY', 'Mercedes-Benz', null, null, 1992);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('CL857CY', null, 'Sorento', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('OO880RR', 'Ford', 'Freestyle', null, 2006);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('IJ429TM', 'Smart', 'Fortwo', 'Puce', 2011);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('AC071ZL', 'Mercedes-Benz', 'M-Class', 'Indigo', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('YB252DL', 'Mitsubishi', 'Lancer Evolution', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('JO448VD', 'Toyota', 'MR2', 'Purple', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('HD493OF', 'Saturn', 'Outlook', 'Mauv', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('PS324HZ', 'MINI', 'Cooper', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('VA009KD', 'Ford', null, 'Fuscia', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('CK457ZI', 'Pontiac', 'Grand Prix', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('NR269RK', null, 'NSX', 'Goldenrod', 1997);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('ND379YO', 'Suzuki', 'Samurai', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('EG277AP', 'Chevrolet', 'Cobalt', 'Khaki', 2008);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('XM377JU', 'Volvo', 'XC70', 'Red', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('OY331HQ', 'Mercury', 'Capri', null, 1986);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('TR731YS', 'Chevrolet', 'LUV', 'Mauv', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('NI545HF', null, 'Accent', null, 1999);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('QA831AV', 'Mitsubishi', 'Montero', 'Aquamarine', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('JR886HD', null, 'Prizm', 'Violet', 1993);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('NG006PT', 'Cadillac', 'XLR-V', 'Turquoise', 2009);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('CR671SD', 'Chevrolet', 'Tahoe', 'Yellow', 2006);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('PB641DV', 'Pontiac', 'Firebird', 'Turquoise', 1969);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('RV963SP', 'Chevrolet', 'S10', null, 1992);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('IR088RB', 'Chevrolet', 'Caprice', 'Fuscia', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('DY835TW', 'BMW', 'X5 M', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('YD201MY', 'Honda', 'Civic', null, 2012);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('WW817ZM', 'Nissan', 'Sentra', 'Violet', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('CR547ME', 'Hyundai', 'XG300', 'Purple', 2001);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('UO897ZV', 'Ford', 'F150', 'Teal', 2006);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('IH601FT', 'Audi', 'Allroad', null, 2001);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('IN616XM', 'Mazda', 'MX-3', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('IP814XV', 'Hummer', 'H3', 'Mauv', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('LI827RX', 'Ford', 'Thunderbird', 'Turquoise', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('RL303JA', 'Chevrolet', 'Camaro', 'Indigo', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('YK761UQ', 'Isuzu', 'Amigo', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('AQ881ZD', 'Pontiac', 'Grand Prix', null, 2000);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('HS048YQ', 'BMW', 'X5', 'Purple', 2009);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('SF750MA', 'Chevrolet', 'Express 1500', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('DO807HE', 'Audi', 'Q7', 'Violet', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('YF927XP', 'Mercedes-Benz', null, null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('XX216FV', null, 'Golf', 'Orange', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('GS169VV', 'Volvo', 'V50', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('VS269BR', 'Volkswagen', 'Scirocco', 'Blue', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('GG809AE', 'Ford', 'Taurus', 'Khaki', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('PH177SA', 'Nissan', 'Pathfinder', null, 1993);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('VT272WZ', 'Subaru', 'Outback', 'Red', 2000);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('XN606SZ', 'Mitsubishi', 'Pajero', null, 2001);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('BF734PH', 'Lotus', 'Exige', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('OF854ZM', 'Honda', 'Civic Si', 'Fuscia', 2005);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('GH079TD', null, 'Elise', 'Purple', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('EG217CE', 'Pontiac', 'Fiero', null, 1987);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('EN660HN', 'Nissan', 'Murano', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('BQ506VF', 'Dodge', 'Ram Van B350', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('DD595JL', 'Chevrolet', 'Suburban 1500', 'Purple', 1994);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('MF212OL', 'Acura', 'CL', 'Red', 1999);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('UO030XP', 'Toyota', 'Prius', 'Khaki', 2009);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('VH238VG', 'Suzuki', 'Swift', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('XW811KC', 'GMC', null, 'Blue', 1999);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('DO110EG', 'Mitsubishi', 'Lancer', null, 2001);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('LI413JD', null, 'A4', 'Goldenrod', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('KS319AR', 'Jeep', 'Grand Cherokee', 'Crimson', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('KN263QX', 'Bentley', 'Continental', 'Pink', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('YS878YN', 'Cadillac', 'Catera', 'Maroon', 2000);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('QT259XS', 'Acura', 'Integra', 'Khaki', 1994);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('XA539YT', 'Pontiac', 'Fiero', 'Maroon', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('RN835CN', null, 'Coachbuilder', 'Khaki', 1990);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('EQ744BU', 'Foose', 'Hemisfear', null, 2007);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('CU784QV', 'Cadillac', 'XLR-V', 'Yellow', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('IE782CU', null, '300M', 'Red', 2002);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('SH828ER', 'Mercedes-Benz', 'SL-Class', 'Teal', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('TI848PV', 'Mercury', 'Mountaineer', 'Goldenrod', 1998);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('WZ943IT', null, 'QX56', 'Green', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('TZ322OZ', 'BMW', 'Z3', null, 1999);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('VU047IK', 'Mitsubishi', 'Sigma', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('JA483MK', 'Mercury', null, 'Green', 2006);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('RR702UC', 'Kia', 'Sephia', 'Pink', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('BQ040FB', 'Mitsubishi', 'Montero', null, 2004);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('CF680FM', 'Pontiac', null, null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('NC861MK', 'BMW', '760', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('PG138VX', 'Chevrolet', 'Silverado 2500', 'Purple', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('NY743PM', 'Plymouth', 'Prowler', null, 1999);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('XM094UO', 'Land Rover', 'Discovery Series II', 'Purple', 2000);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('FT499NE', 'BMW', '650', 'Blue', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('VW190BD', 'Mercedes-Benz', 'CL-Class', 'Violet', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('BS436MQ', 'Mercedes-Benz', 'SL-Class', 'Violet', 2011);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('ER264UF', 'Mitsubishi', null, null, 1998);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('ZD162LG', 'GMC', 'Jimmy', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('VX685FX', 'Nissan', 'Xterra', 'Indigo', 2011);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('AT129LQ', 'Nissan', '350Z', null, 2009);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('HH989RL', null, 'Outlander', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('VJ105OV', 'Mitsubishi', 'Galant', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('JZ991EM', 'Ford', 'F-Series Super Duty', 'Puce', 2012);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('EC335IT', 'Hyundai', 'Genesis', 'Khaki', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('GE769QC', 'Mitsubishi', 'Diamante', 'Yellow', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('DC085YR', 'Nissan', 'Altima', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('SU593AL', null, '900', 'Aquamarine', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('VE591CF', 'Lexus', 'ES', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('RP469RD', 'Subaru', 'Outback', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('MH917TZ', 'Ford', 'Mustang', null, 1984);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('QP805DJ', 'Audi', 'RS 6', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('ZX756XZ', 'Buick', 'Skylark', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('FL959YF', 'Mercedes-Benz', 'W123', 'Purple', 1977);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('RL738WH', 'Chevrolet', 'Corvette', null, 1994);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('AL192QN', 'Aston Martin', 'DB9', 'Crimson', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('SQ436GU', 'Infiniti', 'FX', 'Purple', 2004);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('ZA204UZ', 'Land Rover', 'LR2', null, 2010);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('LB152ZF', 'Subaru', 'Legacy', 'Khaki', 2006);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('DY966JJ', 'Mitsubishi', 'Lancer', 'Mauv', 2002);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('IK461ND', 'Cadillac', 'DeVille', 'Puce', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('PY905CU', null, 'Viper', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('NR926EF', 'Porsche', '944', 'Violet', 1988);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('GJ230HS', 'Dodge', 'Neon', 'Khaki', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('TS408VF', null, 'Town Car', 'Orange', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('KA193XI', 'Pontiac', 'Trans Sport', null, 1991);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('AN510MI', 'Toyota', 'Tundra', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('WF175PG', 'Mitsubishi', 'Challenger', 'Puce', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('WH943VA', 'Mercedes-Benz', 'C-Class', 'Red', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('GN294DO', 'Dodge', 'D150', null, 1992);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('CI964FC', 'Porsche', '911', null, 2013);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('KU029AN', 'Mitsubishi', 'Galant', 'Violet', 1985);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('IU251PI', 'Land Rover', 'Range Rover Sport', 'Teal', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('PO876CY', 'Pontiac', 'Grand Prix', 'Yellow', 1988);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('VG512BX', 'Buick', 'Century', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('EE569UV', 'Cadillac', 'STS', 'Teal', 2010);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('UL551TA', 'Chrysler', '300', 'Indigo', 2006);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('OS200HK', 'Mitsubishi', 'Montero Sport', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('RU092TD', 'Chevrolet', 'Suburban 2500', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('ML040LF', 'Pontiac', 'G8', null, 2008);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('LP800NJ', 'Suzuki', 'Grand Vitara', null, 2001);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('GS336TD', null, null, null, 1970);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('LQ011AI', 'Chevrolet', 'Suburban 1500', 'Puce', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('QY487CD', 'Isuzu', 'i-370', 'Puce', 2007);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('JY994HR', 'Mercury', 'Grand Marquis', 'Khaki', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('GC804JD', 'Ford', 'Econoline E150', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('GV909CB', 'Panoz', 'Esperante', 'Mauv', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('RG475FZ', 'Ford', 'Mustang', null, 1968);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('SK224EV', 'Buick', null, 'Blue', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('XE926IF', 'Mitsubishi', 'Eclipse', 'Crimson', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('ED326ZT', 'Dodge', 'Neon', null, 2004);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('VJ210QL', 'MINI', null, 'Goldenrod', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('PR346ZK', 'Mazda', 'B2500', 'Turquoise', 2001);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('ON761HU', 'Pontiac', 'Torrent', 'Puce', 2009);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('RO550NG', 'Honda', null, 'Red', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('CG292ZE', 'Toyota', 'Prius', 'Blue', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('EF317RF', 'Mazda', 'B-Series', 'Puce', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('QF335GN', 'Ford', 'Crown Victoria', null, 1997);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('ES618EM', 'Mazda', 'Protege', 'Purple', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('PJ837DS', 'Toyota', 'Prius', null, 2005);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('FA910XP', 'Volkswagen', 'Corrado', 'Crimson', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('LO384II', 'Toyota', '4Runner', 'Yellow', 2005);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('SF422XV', 'Cadillac', 'Seville', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('GB637KY', 'Nissan', '300ZX', 'Turquoise', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('EH923FP', 'Chevrolet', 'Corvair 500', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('OI595FM', null, 'Range Rover', 'Green', 2005);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('BI387XW', 'Ford', 'F250', null, 2002);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('QF948MF', 'Volvo', 'XC70', null, 2010);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('AY938JR', 'GMC', '3500', 'Indigo', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('ZZ754ML', 'Pontiac', 'Aztek', 'Blue', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('OM673II', 'Ford', 'E-350 Super Duty', 'Indigo', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('UX968AE', 'Mitsubishi', 'Galant', 'Crimson', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('QM506TG', 'Ford', 'E-Series', 'Violet', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('PK208IO', 'Mercedes-Benz', '400E', 'Maroon', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('ET746RE', 'Lexus', 'LX', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('IY537QY', 'Ford', 'Focus', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('ZI395GH', 'Chevrolet', 'Sportvan G20', 'Mauv', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('KF309SD', 'Chevrolet', 'Silverado 1500', 'Green', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('DU862BN', 'Suzuki', 'Reno', null, 2005);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('OL833JG', 'Audi', 'A6', 'Teal', 2003);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('MK533WS', 'BMW', '7 Series', 'Indigo', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('RD229RX', 'Volkswagen', 'GTI', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('VA168HQ', 'Mitsubishi', 'Pajero', null, 1994);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('RX031UO', null, 'Fusion', 'Orange', 2013);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('AP562FM', 'Audi', 'A8', null, 2000);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('QM010ZO', 'Suzuki', 'Swift', 'Yellow', 1999);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('FJ555VU', 'Suzuki', 'Sidekick', null, 1993);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('AP810BS', 'Mitsubishi', 'Montero', 'Khaki', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('UU796MN', 'Lexus', 'IS', 'Orange', 2011);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('MX141GN', 'Rambler', 'Classic', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('VE369RZ', 'GMC', 'Sierra 1500', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('BP720NR', 'Scion', 'tC', 'Turquoise', 2008);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('BU714FH', null, 'E150', 'Violet', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('SE927DQ', 'Chrysler', '300M', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('DH727ED', 'Volkswagen', 'GLI', 'Pink', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('XB504DQ', 'Toyota', 'Prius', 'Blue', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('HH526YL', 'Jeep', 'Grand Cherokee', null, 2004);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('MM394HJ', 'Ford', 'F450', null, 2008);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('PM398PS', 'BMW', '645', 'Pink', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('HT228AS', 'Dodge', 'Ram 1500', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('YV149XP', 'Pontiac', '1000', null, 1984);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('YL886QX', 'Oldsmobile', 'Alero', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('KS022PT', 'Saab', '900', 'Blue', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('OW211YN', 'Toyota', 'Prius', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('LX248EG', 'Nissan', 'Altima', 'Red', 2010);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('PK089TT', null, 'RVR', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('HB979WG', 'Toyota', 'Venza', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('QS513ET', 'Buick', 'Riviera', 'Orange', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('EF290XK', 'Nissan', 'Maxima', 'Fuscia', 2010);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('SB146IE', 'Kia', 'Sephia', 'Violet', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('UJ840UD', 'Ford', 'E150', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('NW599EI', 'Pontiac', 'Grand Prix', 'Fuscia', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('RC980HH', 'Jeep', 'Patriot', 'Green', 2007);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('RI136ZQ', 'Cadillac', 'DeVille', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('RQ812DF', 'Hummer', 'H2', 'Green', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('VU044RC', 'Mazda', 'CX-9', null, 2010);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('ER951BP', null, 'Club Wagon', 'Red', 1992);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('XC663FY', 'Isuzu', 'Trooper', null, 1998);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('AB139QK', null, null, 'Blue', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('QP452JV', 'Toyota', 'Land Cruiser', 'Yellow', 2013);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('TC471WY', 'Dodge', 'Viper', 'Fuscia', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('FH047RX', 'Nissan', 'JUKE', 'Yellow', 2012);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('XI903KC', 'Pontiac', null, 'Puce', 1998);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('TI732AZ', 'Pontiac', 'Vibe', 'Yellow', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('MJ927LH', 'Chevrolet', 'Prizm', 'Khaki', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('GX785BW', 'Oldsmobile', 'Cutlass', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('MX912TM', 'BMW', 'X5', 'Purple', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('ON503WD', null, 'Grand Am', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('GE278JK', 'Ford', null, null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('VD473QH', 'Lincoln', 'Town Car', 'Red', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('NS590ID', 'Mercedes-Benz', 'M-Class', null, null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('IF585ML', 'Ford', 'Excursion', 'Crimson', 2000);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('DJ170PE', 'Ford', 'F250', 'Teal', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('VF109RJ', 'Oldsmobile', null, 'Violet', null);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('EC349MC', 'Saturn', 'L-Series', 'Pink', 2003);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('OS037MW', 'Toyota', 'Camry', 'Khaki', 2003);
INSERT INTO CARS (plate, brand, model, color, year) VALUES ('EH080IW', 'Rambler', 'Classic', 'Green', null);

-- End transaction
COMMIT;